import { Metadata } from "next";

// static metadata
export const metadata: Metadata = {
    title: "About",
    description: "Generated by create next app",
    keywords: ["Next.js", "218"],
};

export default function AboutPage() {
    return (
        <main>
            About page
        </main>
    )
}

