import { Metadata } from "next";

export const metadata: Metadata = {
    title: "About - 218Next",
    description: "Generated by create next app",
};

export default function AboutPage() {
    return (
        <main>
            About page
        </main>
    )
}
