"use client";

import UserCard from "@/components/cards/UserCard";
import { User } from "@/types/user";
import { Metadata } from "next";


async function wait(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

export const metadata: Metadata = {
    title: "Home",
    description: "Generated by create next app",
};

export default async function HomePage() {

    const res = await fetch("https://jsonplaceholder.typicode.com/users");
    // throw new Error("page was manually crashed!")
    const users: User[] = await res.json();

    return (
        <main>
            <div>
                {users.map((u) => (
                    <UserCard user={u} key={u.id} />
                ))}
            </div>
        </main>
    );
}
